### PR TITLE
pdfload_buffer: only search first 32 bytes

### LINKED ISSUE #4885: vips_image_new_from_buffer() incorrectly tries to read HEIF buffer as PDF
## Bug report

When `vips_image_new_from_buffer()` is used on an HEIF input buffer, it attempts to load the buffer as PDF. The error raised is:
```
vips_image_new_from_buffer() failed: pdfload: file not in PDF format or corrupted
pdfload: source: unable to load
```

I think this happens because when libvips tries to determine the correct loader class for the buffer, the `vips__pdf_is_a_buffer()` function is called before its HEIF equivalent. That alone is not a problem. The problem is that as the second argument to `vips__pdf_is_a_buffer()` is the entire length of the buffer is passed, when it should be 32 as per https://github.com/libvips/libvips/issues/3339#issuecomment-1814212565

**To Reproduce**

I have created (AI-generated) a dockerised project with a single .cpp file and the input image - https://github.com/violetviolinist/libvips-bug-report

**Expected behavior**
`vips_image_new_from_buffer()` should correctly read the input buffer as a HEIF buffer

**Actual behavior**
`vips_image_new_from_buffer()` tries to read the input buffer as a PDF buffer

**Environment**
 - OS: debian 12 bookworm
 - Vips: latest (built from source from the main branch with PDFium and libheif support enabled)

**Edit**: Added context about libvips build

### PR DESCRIPTION
**Pull request by jcupitt**
The `is_a` detector for pdf buffer load was being passed and then searching the whole input buffer for the `%PDF` marker. This could lead to binary files being incorrectly recognised as PDF.

Closes: https://github.com/libvips/libvips/issues/4885

Thanks @violetviolinist

### CODE REVIEW

**Comment by jcupitt** [comment]
This only shows up as a problem with pdfium load, curiously. pdfium and poppler load are the same priority, but pdfium will sort earlier in the priority order.

I read the other `is_a_buffer` testers, and they all limit the search window correctly.

File: libvips/foreign/pdf.c [hunk 1]
```diff
@@ -59,7 +59,8 @@ vips__pdf_is_a_buffer(const void *buf, size_t len)
 	if (len < 4)
 		return FALSE;
 
-	for (size_t i = 0; i < len - 4; i++)
+	// expect the %PDF marker in the first 32 bytes
+	for (size_t i = 0; i < VIPS_MIN(32, len - 4); i++)
```
Comment (lovell) [inline libvips/foreign/pdf.c]: Perhaps use the existing `MAX_OFFSET` value here instead of a "magic" number?

**Review by lovell — COMMENTED** [review]
See also https://github.com/libvips/libvips/issues/3339

File: libvips/foreign/pdf.c (hunk 1 above)
Comment (jcupitt) [reply libvips/foreign/pdf.c]: Oop! Duh, fixed, thanks!

**Review by kleisauke — APPROVED** [review]
