### PR TITLE
draw_flood: reject out-of-bounds start point

### LINKED ISSUE #4869: potential heap-buffer-overflow in flood_all
Found with #4863

I think it's probably because of missing bounds checks in `draw_flood`.

### Reproducer
libvips must be built with ASAN:
```
meson setup build -Db_sanitize=address
meson compile -C build
```
And then the following `draw_flood` command crashes:
```
./build/tools/vips black test.png 2 2
./build/tools/vips draw_flood test.png 128 5 0
```

### ASAN output
```
==76290==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000020815 at pc 0x0001034ccd2c bp 0x00016d986870 sp 0x00016d986868
READ of size 1 at 0x603000020815 thread T0
    #0 0x0001034ccd28 in flood_all+0x1ec0 (libvips.42.dylib:arm64+0x438d28)
    #1 0x0001034cda74 in vips_draw_flood_build+0x460 (libvips.42.dylib:arm64+0x439a74)
    #2 0x00010350a6ec in vips_object_build+0xd8 (libvips.42.dylib:arm64+0x4766ec)
    #3 0x000103539cbc in vips_call_argv+0x168 (libvips.42.dylib:arm64+0x4a5cbc)
    #4 0x00010247b2b0 in main+0xb30 (vips:arm64+0x1000032b0)
    #5 0x000182279d50  (<unknown module>)
```

### Environment
- libvips master (7fab325d2)
- macOS, M3 Pro (aarch64)
-  Highway enabled

### PR DESCRIPTION
**Pull request by dloebl**
Resolves #4869 
`draw_flood` did not properly validate the start point coordinates, causing potential OOB reads when the start point was outside the image. Add bounds checks to `vips_draw_flood_build` before any pixel access.

### CODE REVIEW

**Review by lovell — APPROVED** [review]
Thanks for finding and fixing this.

File: libvips/draw/draw_flood.c [hunk 1]
```diff
@@ -490,6 +490,15 @@ vips_draw_flood_build(VipsObject *object)
 			drawflood->test, draw->image))
 		return -1;
 
+	if (drawflood->x < 0 ||
+		drawflood->x >= draw->image->Xsize ||
+		drawflood->y < 0 ||
```
Comment (kleisauke) [inline libvips/draw/draw_flood.c]: `drawflood->x` and `drawflood->y` is already clipped to a minimum of 0.
https://github.com/libvips/libvips/blob/afdf836be5ed98e03d0435992ac1c36ac97b8785/libvips/draw/draw_flood.c#L570
https://github.com/libvips/libvips/blob/afdf836be5ed98e03d0435992ac1c36ac97b8785/libvips/draw/draw_flood.c#L577

```suggestion
	if (drawflood->x >= draw->image->Xsize ||
```
